### ISSUE TITLE
Error on New Docker Install

### ISSUE THREAD

**Issue by beraj** [HugoFara/lwt-docker-installer#5]
Good Morning,

Recently came across this project which looked very interesting for my Spanish learning journey! I was able to spin up an instance of LWT using the docker setup steps.  However, I get the following error when trying to setup my first language.  Do you have any ideas?  This can probably be labelled as a question.

Fatal Error in SQL Query: INSERT INTO languages ( LgName, LgDict1URI, LgDict2URI, LgGoogleTranslateURI, LgExportTemplate, LgTextSize, LgCharacterSubstitutions, LgRegexpSplitSentences, LgExceptionsSplitSentences, LgRegexpWordCharacters, LgRemoveSpaces, LgSplitEachChar, LgRightToLeft, LgTTSVoiceAPI, LgShowRomanization ) VALUES('Spanish', 'https://de.glosbe.com/es/en/lwt_term?lwt_popup=1', NULL, 'https://translate.google.com/?ie=UTF-8&sl=es&tl=en&text=lwt_term', NULL, '150', '', '.!?:;', '', '\\\'a-zA-ZÀ-ÖØ-öø-ȳЀ-ӹ', 0, 0, 0, NULL, 1)

Error Code & Message: [1054] Unknown column 'LgTTSVoiceAPI' in 'field list'

**Comment by HugoFara** [comment]
Good morning, it seems that the database did not update correctly. It think it comes from a bug we fixed today (HugoFara/lwt#189)! You can do any of the following:

- Update the project's image (the fix will be included). Go to the folder where you have you Dockerfile and type

```bash
docker compose down
docker compose pull
docker compose up -d
```

- Download the latest release (2.9.1)

I hope that will help you!

**Comment by beraj** [comment]
Thanks for the quick reply.  I gave that a shot, but still running into same error:

Error Code & Message: [1048] Column 'LgTTSVoiceAPI' cannot be null

Here is the server info if at all helpful:

![image](https://github.com/HugoFara/lwt-docker-installer/assets/12865742/0780c0d6-8ee9-4026-afc8-413ddd147710)

**Comment by HugoFara** [comment]
It's a real bug indeed, I was able to reproduce it.

For now you can avoid it by:

1. Go to the language creation tab.
2. Fill any value in the voice API (see picture)
![voice API field](https://github.com/HugoFara/lwt-docker-installer/assets/72709893/b5ac8f7c-6e4c-4c57-8a1f-abba81a33fba)
3. Save the language.

If you want to have the audio back for the language: 

1. Edit the language you just created
2. Remove the value in the Voice API field.

I'm working on a fix at the same time.

**Comment by HugoFara** [comment]
The fix was published as well, you can update at any time, have a good day!
